spring.datasource.url=jdbc:mysql://localhost:3306/shopdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=appuser
spring.datasource.password=app123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

# 32+ bytes key encoded in Base64 for HS256
app.jwt.secret=VGhpc0lzQVNlY3VyZUFuZExvbmdFbm91Z2hCYXNlNjRLZXlGb3JKV1QxMjM0NTY=
app.jwt.expiration-ms=86400000
